resources:
- ../../../base/default/gatus/
patches:
- target:
    kind: Ingress
    name: gatus-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: gatus.deskcube.int.sambaum.ch
    - op: replace
      path: /spec/tls/0/hosts
      value: [gatus.deskcube.int.sambaum.ch]
    - op: replace
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: letsencrypt-production
