resources:
- deployment.yaml
- regular-secret.yaml
- configmap.yaml

# Kustomize generated resources
configMapGenerator:
- name: generated-config
  literals:
  - color=blue
  files:
  - extra-config.properties
- name: showcase-script
  files:
  - showcase-script.sh

secretGenerator:
- name: generated-secret
  literals:
  - token=abcdef
  files:
  - credentials.txt
  - cred=credentials.txt
  - password.txt
  - password=password.txt

# existing secret credentials. this will create a secret with keys rootUser and rootPassword
# Attention: if password.txt is SOPS encrypted, kustomize will NOT decrypt it automatically! hence, this does not work with SOPS encrypted files.
secretGenerator:
- name: my-credentials
  literals:
  - rootUser=user1
  files:
  - rootPassword=password.txt
