apiVersion: 1
datasources:
- name: InfluxDB
  type: influxdb
  url: http://influxdb-service:8086
  jsonData:
    version: Flux
    organization: sam
  secureJsonData:
    token: NyR_zJtKbGA53y_VWXZ12HzgrjT9fDEqHAqLxd_NBFYcoPxR2Z6v6GvEhTXoEb2y-dnsdI2U_2vsvwHtODDBlw== # Read-only 
