resources:
- ../../../base/monitoring/kube-prometheus-stack/
- prometheus-blackbox-exporter-probe.yaml
patches:
- target:
    kind: HelmRelease
    name: kube-prometheus-stack
  path: helmrelease-patch.yaml
- target:
    kind: Ingress
    name: thanos-query-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: thanos-query.dumpster.int.sambaum.ch
    - op: replace
      path: /spec/tls/0/hosts
      value: [thanos-query.dumpster.int.sambaum.ch]
    - op: replace
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: letsencrypt-production

configMapGenerator:
- name: influxdb-datasource
  namespace: monitoring
  files:
  - influxdb-datasource.yaml
  options:
    labels:
      grafana_datasource: "1"
- name: thanos-datasources-external
  namespace: monitoring
  files:
  - thanos-datasources.yaml
  options:
    labels:
      grafana_datasource: "1"
