resources:
- ../../../base/monitoring/kube-prometheus-stack/
- prometheus-blackbox-exporter-probe.yaml
patches:
- target:
    kind: HelmRelease
    name: kube-prometheus-stack
  path: helmrelease-patch.yaml
