resources:
- ../../../base/default/fourgaboards/
patches:
- target:
    kind: Deployment
    name: fourgaboards
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: https://fourgaboards.int.sambaum.ch
- target:
    kind: Ingress
    name: fourgaboards-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: fourgaboards.int.sambaum.ch
    - op: replace
      path: /spec/tls/0/hosts/0
      value: fourgaboards.int.sambaum.ch
    - op: replace
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: letsencrypt-production
