apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: monitoring
spec:
  releaseName: prometheus-blackbox-exporter
  interval: 30m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: "11.8.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  values:
    fullnameOverride: blackbox-exporter
    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s
      labels:
        release: kube-prometheus-stack
    config:
      modules:
        http_check_woocommerce_cbee:
          prober: http
          timeout: 5s
          http:
            method: GET
            preferred_ip_protocol: "ip4"
            valid_status_codes: [ 200 ]
            follow_redirects: true
            # fail_if_not_matches_regexp:
            # - "cbee.ch"
            tls_config:
              insecure_skip_verify: false
        http_checkout:
          prober: http
          timeout: 5s
          http:
            method: GET
            valid_status_codes: [ 200, 302 ]
