# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: automation
#   namespace: flux-system
# spec:
#   interval: 30m
#   dependsOn:
#     - name: apps
#   path: ./apps/base/automation
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
