resources:
- ../../../base/default/httpbin/
patches:
- target:
    kind: Ingress
    name: httpbin-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: httpbin.int.sambaum.ch
    - op: replace
      path: /spec/tls/0/hosts
      value: [httpbin.int.sambaum.ch]
    - op: replace
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: letsencrypt-production
