apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/minio/
- pv-pvc.yaml
patches:
- target:
    kind: HelmRelease
    name: minio
  patch: |-
    - op: replace
      path: /spec/values/persistence/existingClaim
      value: truenas-thanos-minio-pvc
    - op: replace
      path: /spec/values/persistence/subPath
      value: thanos-minio-dumpster
    - op: replace
      path: /spec/values/consoleIngress/hosts/0
      value: thanos-minio-console.dumpster.int.sambaum.ch
    - op: replace
      path: /spec/values/consoleIngress/tls/0/hosts/0
      value: thanos-minio-console.dumpster.int.sambaum.ch
    - op: replace
      path: /spec/values/consoleIngress/annotations/cert-manager.io~1cluster-issuer
      value: letsencrypt-production
    - op: replace
      path: /spec/values/ingress/hosts/0
      value: thanos-minio-api.dumpster.int.sambaum.ch
    - op: replace
      path: /spec/values/ingress/tls/0/hosts/0
      value: thanos-minio-api.dumpster.int.sambaum.ch
    - op: replace
      path: /spec/values/ingress/annotations/cert-manager.io~1cluster-issuer
      value: letsencrypt-production

- target:
    kind: Job
    name: fix-minio-pv-permissions
  patch: |-
    - op: replace
      path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
      value: truenas-thanos-minio-pvc
