resources:
- ../../../base/monitoring/kube-prometheus-stack/
patches:
- target:
    kind: HelmRelease
    name: kube-prometheus-stack
  path: helmrelease-patch.yaml
- target:
    kind: Ingress
    name: thanos-query-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: thanos-query.deskcube.int.sambaum.ch
    - op: replace
      path: /spec/tls/0/hosts
      value: [thanos-query.deskcube.int.sambaum.ch]
secretGenerator:
- name: thanos-objstore
  namespace: monitoring
  behavior: replace
  files:
  - objstore.yml
  type: Opaque
  options:
    disableNameSuffixHash: true # because the helm chart (sidecar) references it directly by name and expects it to be stable.
