resources:
  - ../../../base/core/portainer/
patches:
  - target:
      kind: Ingress
      name: portainer-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: portainer.dumpster.int.sambaum.ch
      - op: replace
        path: /spec/tls/0/hosts
        value: [portainer.dumpster.int.sambaum.ch]
      - op: replace
        path: /metadata/annotations/flame.pawelmalak~1url
        value: https://portainer.dumpster.int.sambaum.ch
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-staging
  - target:
      kind: HelmRelease
      name: portainer
    patch: |-
      - op: replace
        path: /spec/values/ingress/hosts/0/host
        value: portainer.dumpster.int.sambaum.ch
      - op: replace
        path: /spec/values/ingress/tls/0/hosts/0
        value: portainer.dumpster.int.sambaum.ch
      - op: replace
        path: /spec/values/ingress/annotations/flame.pawelmalak~1url
        value: https://portainer.dumpster.int.sambaum.ch
      - op: replace
        path: /spec/values/ingress/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-staging
